version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.0
  cli: circleci/circleci-cli@0.1.9

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  publishers_clearing_house:
    executor: cli/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - orb-tools/pack
      - orb-tools/validate
      - orb-tools/publish:
          orb-ref: "cst/framework@dev:${CIRCLE_SHA1:0:7}"
      - orb-tools/publish:
          orb-ref: "cst/framework@dev:${CIRCLE_BRANCH}"
      - persist_to_workspace:
          root: .
          paths: orb.yml

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - publishers_clearing_house
      - orb-tools/lint

      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: cst/framework
          context: <publishing-context>
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - publishers_clearing_house
          filters:
            branches:
              only:
                - main
